# Define platform for your project
platform :ios, '13.0'

target 'HeyloIos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HeyloIos

  # Firebase
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'FirebaseFunctions'
  pod 'FirebaseMessaging'
  pod 'FirebaseAppCheck'

  # Add the Firebase SDK for Google Analytics
  pod 'FirebaseAnalytics'

  # UI and Image Handling
  pod 'SDWebImage'
  pod 'SkeletonView'

  # Networking
  pod 'Alamofire', '~> 5.6.4'

  # Security
  pod 'KeychainAccess'

  # For Analytics without IDFA collection capability, use this pod instead
  # pod 'FirebaseAnalyticsWithoutAdIdSupport'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'

      # More aggressive fixes for sandbox issues
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'

      # Disable App Sandbox for all pods
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      config.build_settings['ENABLE_APP_SANDBOX'] = 'NO'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end