version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: heylo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: heylo-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: always

volumes:
  redis-data:
